/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

export interface AuditResultQueueStatusDto {
  /** Number of pending audit results in queue */
  pendingCount: number;
  /** List of payment IDs waiting to be synced */
  pendingPaymentIds: string[];
}
