/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { BootstrapDemoWalletDtoRescueMode } from './bootstrapDemoWalletDtoRescueMode';

export interface BootstrapDemoWalletDto {
  /** Rescue orientation to prepare for demo runs */
  rescueMode: BootstrapDemoWalletDtoRescueMode;
  /** Force a new bootstrap run even when a successful run already exists */
  force?: boolean;
  /**
   * Minimum USD amount below which no borrow action will be created
   * @minimum 1
   */
  minBorrowUsd?: number;
}
