/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

export type ComplianceDetailResponseDtoStatus = typeof ComplianceDetailResponseDtoStatus[keyof typeof ComplianceDetailResponseDtoStatus];


export const ComplianceDetailResponseDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  BLOCKED: 'BLOCKED',
  RELEASED: 'RELEASED',
  FROZEN: 'FROZEN',
  REFUNDED: 'REFUNDED',
} as const;
