/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */
import type { ComplianceDetailResponseDtoSenderCompliance } from './complianceDetailResponseDtoSenderCompliance';
import type { ComplianceDetailResponseDtoStatus } from './complianceDetailResponseDtoStatus';

export interface ComplianceDetailResponseDto {
  paymentId: string;
  status: ComplianceDetailResponseDtoStatus;
  /** @nullable */
  senderCompliance: ComplianceDetailResponseDtoSenderCompliance;
  recipientCompliance: unknown[];
  /** @nullable */
  onChainHash: string | null;
  verified: boolean;
  /** Whether audit result is pending sync from Redis to DB */
  pendingSync: boolean;
}
