/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { CreateRescueWorkflowLogDtoMetadata } from './createRescueWorkflowLogDtoMetadata';
import type { CreateRescueWorkflowLogDtoWorkflowId } from './createRescueWorkflowLogDtoWorkflowId';

export interface CreateRescueWorkflowLogDto {
  /** Long workflow log text generated for this rescue execution run */
  logText: string;
  /** CRE workflow ID that produced this log */
  workflowId?: CreateRescueWorkflowLogDtoWorkflowId;
  /** Optional workflow run identifier */
  runId?: string;
  /** Additional structured metadata */
  metadata?: CreateRescueWorkflowLogDtoMetadata;
}
