/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { DistributionControllerGetPendingBatches200BatchesItem } from './distributionControllerGetPendingBatches200BatchesItem';

export type DistributionControllerGetPendingBatches200 = {
  batches?: DistributionControllerGetPendingBatches200BatchesItem[];
};
