/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export interface FinalizeWithdrawalDto {
  sessionId: string;
  txHash: string;
  logIndex: number;
}
