/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

export interface FundDemoWalletDto {
  /** Target native ETH balance on Ethereum Sepolia */
  ethereumSepoliaGasEth?: string;
  /** Target native ETH balance on Base Sepolia */
  baseSepoliaGasEth?: string;
  /** Target WETH balance on Ethereum Sepolia */
  ethereumSepoliaWethTarget?: string;
  /** Target USDC balance on Ethereum Sepolia */
  ethereumSepoliaUsdcTarget?: string;
  /** Target WETH balance on Base Sepolia */
  baseSepoliaWethTarget?: string;
  /** Target USDC balance on Base Sepolia */
  baseSepoliaUsdcTarget?: string;
}
