/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { OhlcControllerGetOhlc200CandlesItem } from './ohlcControllerGetOhlc200CandlesItem';

export type OhlcControllerGetOhlc200 = {
  windowStart?: number;
  windowEnd?: number;
  count?: number;
  hash?: string;
  candles?: OhlcControllerGetOhlc200CandlesItem[];
};
