/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type OhlcControllerGetOhlcSource = typeof OhlcControllerGetOhlcSource[keyof typeof OhlcControllerGetOhlcSource];


export const OhlcControllerGetOhlcSource = {
  internal: 'internal',
  chainlink: 'chainlink',
} as const;
