/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type OrderControllerGetUserOrdersStatus = typeof OrderControllerGetUserOrdersStatus[keyof typeof OrderControllerGetUserOrdersStatus];


export const OrderControllerGetUserOrdersStatus = {
  OPEN: 'OPEN',
  SETTLED: 'SETTLED',
  REJECTED: 'REJECTED',
} as const;
