/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

export type PaymentResponseDtoTokenType = typeof PaymentResponseDtoTokenType[keyof typeof PaymentResponseDtoTokenType];


export const PaymentResponseDtoTokenType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
