/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentResponseDto } from './paymentResponseDto';

export interface PaymentListResponseDto {
  items: PaymentResponseDto[];
  total: number;
  page: number;
  pageSize: number;
}
