/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

/**
 * @nullable
 */
export type PaymentResponseDtoAuditResult = { [key: string]: unknown } | null;
