/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentResponseDtoAuditResult } from './paymentResponseDtoAuditResult';
import type { PaymentResponseDtoStatus } from './paymentResponseDtoStatus';
import type { PaymentResponseDtoTokenType } from './paymentResponseDtoTokenType';

export interface PaymentResponseDto {
  id: number;
  paymentId: string;
  sender: string;
  recipients: string[];
  amounts: string[];
  totalAmount: string;
  tokenType: PaymentResponseDtoTokenType;
  tokenAddress: string;
  auditMask: number;
  status: PaymentResponseDtoStatus;
  /** @nullable */
  auditResult: PaymentResponseDtoAuditResult;
  /** @nullable */
  complianceHash: string | null;
  /** @nullable */
  finalDecision: number | null;
  /** @nullable */
  anchoredAt: string | null;
  recipientCount: number;
  blockNumber: string;
  transactionHash: string;
  created_at: string;
  updated_at: string;
  /** Whether audit result is pending sync from Redis to DB */
  pendingSync: boolean;
}
