/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { Cell } from './cell';

export interface PlaceOrderDto {
  cell: Cell;
  marketId: string;
  amount: string;
}
