/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

export type PositionsControllerGetRiskSnapshotParams = {
/**
 * Max acceptable age of latest snapshot for stale flag
 * @minimum 1
 */
maxAgeSec?: number;
};
