/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

export type PositionsControllerGetOraclePriceChainKey = typeof PositionsControllerGetOraclePriceChainKey[keyof typeof PositionsControllerGetOraclePriceChainKey];


export const PositionsControllerGetOraclePriceChainKey = {
  'ethereum-sepolia': 'ethereum-sepolia',
  'base-sepolia': 'base-sepolia',
} as const;
