/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { PositionsControllerGetOraclePriceChainKey } from './positionsControllerGetOraclePriceChainKey';

export type PositionsControllerGetOraclePriceParams = {
/**
 * Supported chain key
 */
chainKey: PositionsControllerGetOraclePriceChainKey;
/**
 * Asset token address
 */
asset: string;
};
