/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

export type RelayControllerListRelayJobsStatus = typeof RelayControllerListRelayJobsStatus[keyof typeof RelayControllerListRelayJobsStatus];


export const RelayControllerListRelayJobsStatus = {
  pending: 'pending',
  running: 'running',
  success: 'success',
  dead: 'dead',
} as const;
