/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { RelayControllerListRelayJobsStatus } from './relayControllerListRelayJobsStatus';

export type RelayControllerListRelayJobsParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Page size (1-100)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Relay status filter
 */
status?: RelayControllerListRelayJobsStatus;
/**
 * Source/destination chain id filter
 * @minimum 1
 */
chainId?: number;
};
