/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { RescuesControllerListRescuesStatus } from './rescuesControllerListRescuesStatus';

export type RescuesControllerListRescuesParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Page size (1-100)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * User wallet address filter
 */
user?: string;
/**
 * Rescue status filter
 */
status?: RescuesControllerListRescuesStatus;
/**
 * Chain id filter
 * @minimum 1
 */
chainId?: number;
};
