/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

export type RescuesControllerListRescuesStatus = typeof RescuesControllerListRescuesStatus[keyof typeof RescuesControllerListRescuesStatus];


export const RescuesControllerListRescuesStatus = {
  none: 'none',
  in_progress: 'in_progress',
  completed: 'completed',
  failed: 'failed',
  partial: 'partial',
  cancelled: 'cancelled',
} as const;
