/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

/**
 * GET alias for what-if prices on Ethereum Sepolia
 */
export type RiskSnapshotQueryDtoEthereumSepolia = { [key: string]: unknown };
