/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { RiskSnapshotQueryDtoBaseSepolia } from './riskSnapshotQueryDtoBaseSepolia';
import type { RiskSnapshotQueryDtoEthereumSepolia } from './riskSnapshotQueryDtoEthereumSepolia';
import type { RiskSnapshotQueryDtoWhatIfPrices } from './riskSnapshotQueryDtoWhatIfPrices';

export interface RiskSnapshotQueryDto {
  /**
   * Max acceptable age (seconds) of latest position snapshot
   * @minimum 1
   */
  maxAgeSec?: number;
  /** Optional what-if price overrides in wad, scoped by chain and asset address */
  whatIfPrices?: RiskSnapshotQueryDtoWhatIfPrices;
  /** GET alias for what-if prices on Ethereum Sepolia */
  'ethereum-sepolia'?: RiskSnapshotQueryDtoEthereumSepolia;
  /** GET alias for what-if prices on Base Sepolia */
  'base-sepolia'?: RiskSnapshotQueryDtoBaseSepolia;
}
