/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type SettlementControllerGetCommittedBatchesParams = {
/**
 * Unix timestamp (seconds) - window start
 */
windowStart: number;
/**
 * Unix timestamp (seconds) - window end
 */
windowEnd: number;
};
