/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type SettlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome = typeof SettlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome[keyof typeof SettlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome];


export const SettlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome = {
  WIN: 'WIN',
  LOSS: 'LOSS',
} as const;
