/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { SettlementControllerGetPendingBatches200BatchesItem } from './settlementControllerGetPendingBatches200BatchesItem';

export type SettlementControllerGetPendingBatches200 = {
  batches?: SettlementControllerGetPendingBatches200BatchesItem[];
};
