/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { SimulateApiGuardDtoBaseSepolia } from './simulateApiGuardDtoBaseSepolia';
import type { SimulateApiGuardDtoEthereumSepolia } from './simulateApiGuardDtoEthereumSepolia';
import type { SimulateApiGuardDtoExecutionChainKey } from './simulateApiGuardDtoExecutionChainKey';
import type { SimulateApiGuardDtoWhatIfPrices } from './simulateApiGuardDtoWhatIfPrices';

export interface SimulateApiGuardDto {
  /** Execution chain key used by planner for source withdrawal */
  executionChainKey?: SimulateApiGuardDtoExecutionChainKey;
  /**
   * Max acceptable age (seconds) for latest position snapshot
   * @minimum 1
   */
  maxAgeSec?: number;
  /** Force plan to cross-chain even when source/target appear on same chain */
  forceCrossChain?: boolean;
  /** Optional source adapter override */
  sourceAdapter?: string;
  /** Optional target adapter override */
  targetAdapter?: string;
  /**
   * Early warning health factor threshold in bps
   * @minimum 10000
   */
  earlyWarningHfBps?: number;
  /**
   * Hard minimum health factor threshold in bps
   * @minimum 10000
   */
  onchainHfMinBps?: number;
  /**
   * Minimum source HF floor after withdrawal, in bps
   * @minimum 10000
   */
  sourceFloorHfBps?: number;
  /**
   * Target HF in bps used to size rescue action amount
   * @minimum 10000
   */
  targetHfBps?: number;
  /**
   * Reserve cap in bps (portion protected from withdrawal)
   * @minimum 0
   * @maximum 10000
   */
  reserveCapBps?: number;
  /**
   * Maximum rescue notional in USD
   * @minimum 1
   */
  maxRescueNotionalUsd?: number;
  /**
   * Minimum action threshold in USD
   * @minimum 0
   */
  minActionUsd?: number;
  /** Allow cross-chain planning */
  allowCrossChain?: boolean;
  /** Optional what-if price overrides in wad, scoped by chain and asset address */
  whatIfPrices?: SimulateApiGuardDtoWhatIfPrices;
  /** GET alias for what-if prices on Ethereum Sepolia */
  'ethereum-sepolia'?: SimulateApiGuardDtoEthereumSepolia;
  /** GET alias for what-if prices on Base Sepolia */
  'base-sepolia'?: SimulateApiGuardDtoBaseSepolia;
}
