/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

/**
 * Execution chain key used by planner for source withdrawal
 */
export type SimulateApiGuardDtoExecutionChainKey = typeof SimulateApiGuardDtoExecutionChainKey[keyof typeof SimulateApiGuardDtoExecutionChainKey];


export const SimulateApiGuardDtoExecutionChainKey = {
  'ethereum-sepolia': 'ethereum-sepolia',
  'base-sepolia': 'base-sepolia',
} as const;
