/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional what-if price overrides in wad, scoped by chain and asset address
 */
export type SimulateApiGuardDtoWhatIfPrices = { [key: string]: unknown };
