/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type StrategyControllerGetCurrentRegime200 = {
  regimeId?: number;
  fortressSpreadBps?: number;
  maxMultiplier?: number;
  effectiveTs?: number;
  volatilityIndex?: string;
  regimeName?: string;
};
