/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateUserDto {
  /** Email address */
  email?: string;
  /** Full name of the user */
  fullName?: string;
  /** Phone number */
  phoneNumber?: string;
}
