/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

/**
 * Final decision
 */
export type UpdateAuditResultDtoFinalDecision = typeof UpdateAuditResultDtoFinalDecision[keyof typeof UpdateAuditResultDtoFinalDecision];


export const UpdateAuditResultDtoFinalDecision = {
  PASS: 'PASS',
  BLOCK: 'BLOCK',
} as const;
