/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

/**
 * Compliance audit result JSON object
 */
export type UpdateAuditResultDtoAuditResult = { [key: string]: unknown };
