/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateAuditResultDtoAuditResult } from './updateAuditResultDtoAuditResult';
import type { UpdateAuditResultDtoFinalDecision } from './updateAuditResultDtoFinalDecision';

export interface UpdateAuditResultDto {
  /** Payment ID */
  paymentId: string;
  /** Compliance audit result JSON object */
  auditResult: UpdateAuditResultDtoAuditResult;
  /** Final decision */
  finalDecision: UpdateAuditResultDtoFinalDecision;
  /** Block reason if failed */
  blockReason?: string;
}
