/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import type { UpsertUserCreRegistrationDtoQueuePriority } from './upsertUserCreRegistrationDtoQueuePriority';
import type { UpsertUserCreRegistrationDtoWorkflowId } from './upsertUserCreRegistrationDtoWorkflowId';

export interface UpsertUserCreRegistrationDto {
  /** Workflow strategy to run for this user */
  workflowId: UpsertUserCreRegistrationDtoWorkflowId;
  /**
   * Health-factor threshold in basis points (1.00 = 10000)
   * @minimum 1000
   * @maximum 100000
   */
  hfThresholdBps: number;
  /** Rescue priority ordering */
  queuePriority: UpsertUserCreRegistrationDtoQueuePriority;
  /**
   * Budget cap in USD
   * @minimum 0.01
   * @maximum 1000000000
   */
  budgetCapUsd: number;
  /** Mutation source */
  source?: string;
  /** Actor identifier for audit trail */
  updatedBy?: string;
}
