/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */
import type { UserResponseDtoKycIdType } from './userResponseDtoKycIdType';
import type { UserResponseDtoKycStatus } from './userResponseDtoKycStatus';

export interface UserResponseDto {
  /** User ID */
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  /** Wallet address */
  walletAddress: string;
  /** Email address */
  email?: string;
  /** Full name */
  fullName?: string;
  /** Phone number */
  phoneNumber?: string;
  /** KYC status */
  kycStatus: UserResponseDtoKycStatus;
  /** KYC ID type */
  kycIdType?: UserResponseDtoKycIdType;
  /** KYC ID number */
  kycIdNumber?: string;
  /** KYC verification timestamp */
  kycVerifiedAt?: string;
  /** Created at timestamp */
  createdAt: string;
  /** Updated at timestamp */
  updatedAt: string;
}
