/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

/**
 * KYC status
 */
export type UserResponseDtoKycStatus = typeof UserResponseDtoKycStatus[keyof typeof UserResponseDtoKycStatus];


export const UserResponseDtoKycStatus = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
} as const;
