/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

/**
 * KYC ID type
 */
export type UserResponseDtoKycIdType = typeof UserResponseDtoKycIdType[keyof typeof UserResponseDtoKycIdType];


export const UserResponseDtoKycIdType = {
  PASSPORT: 'PASSPORT',
  NATIONAL_ID: 'NATIONAL_ID',
  DRIVER_LICENSE: 'DRIVER_LICENSE',
  Identity_Card: 'Identity Card',
} as const;
