/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Finance OS API
 * OpenAPI spec version: 0.0.1
 */

export interface VerificationSessionResponse {
  /** KYC verification URL */
  url: string;
}
