/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type WorkerControllerGetVolatilityRegimesParams = {
/**
 * From block timestamp (Unix timestamp in seconds)
 */
fromTimestamp: number;
/**
 * To block timestamp (Unix timestamp in seconds)
 */
toTimestamp: number;
/**
 * Page number (1-based)
 */
page?: number;
/**
 * Page size (max 100)
 */
pageSize?: number;
};
