/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Tapfun Bot API
 * OpenAPI spec version: 0.0.12
 */

export type WorkerControllerGetSettlementBatches200 = {
  data?: unknown[];
  page?: number;
  pageSize?: number;
  total?: number;
};
