/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Reprieve Backend API
 * Debug and integration APIs for positions, rescues, and relay history
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BootstrapDemoWalletDto,
  CreRegistrationsControllerListRegistrationRevisionsParams,
  CreateRescueWorkflowLogDto,
  FundDemoWalletDto,
  GenerateDemoWalletDto,
  PositionsControllerGetRiskSnapshotParams,
  RelayControllerListRelayJobsParams,
  RescuesControllerListRescueWorkflowLogsParams,
  RescuesControllerListRescuesParams,
  UpsertUserCreRegistrationDto,
} from "./models";

import { customClient } from "./custom-client";
import type { ErrorType, BodyType } from "./custom-client";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create or update the active CRE registration for a user
 */
export type creRegistrationsControllerUpsertRegistrationResponse200 = {
  data: void;
  status: 200;
};

export type creRegistrationsControllerUpsertRegistrationResponseSuccess =
  creRegistrationsControllerUpsertRegistrationResponse200 & {
    headers: Headers;
  };
export type creRegistrationsControllerUpsertRegistrationResponse =
  creRegistrationsControllerUpsertRegistrationResponseSuccess;

export const getCreRegistrationsControllerUpsertRegistrationUrl = (
  address: string,
) => {
  return `/v1/users/${address}/cre-registration`;
};

export const creRegistrationsControllerUpsertRegistration = async (
  address: string,
  upsertUserCreRegistrationDto: UpsertUserCreRegistrationDto,
  options?: RequestInit,
): Promise<creRegistrationsControllerUpsertRegistrationResponse> => {
  return customClient<creRegistrationsControllerUpsertRegistrationResponse>(
    getCreRegistrationsControllerUpsertRegistrationUrl(address),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(upsertUserCreRegistrationDto),
    },
  );
};

export const getCreRegistrationsControllerUpsertRegistrationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof creRegistrationsControllerUpsertRegistration>>,
    TError,
    { address: string; data: BodyType<UpsertUserCreRegistrationDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof creRegistrationsControllerUpsertRegistration>>,
  TError,
  { address: string; data: BodyType<UpsertUserCreRegistrationDto> },
  TContext
> => {
  const mutationKey = ["creRegistrationsControllerUpsertRegistration"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof creRegistrationsControllerUpsertRegistration>>,
    { address: string; data: BodyType<UpsertUserCreRegistrationDto> }
  > = (props) => {
    const { address, data } = props ?? {};

    return creRegistrationsControllerUpsertRegistration(
      address,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type CreRegistrationsControllerUpsertRegistrationMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof creRegistrationsControllerUpsertRegistration>>
  >;
export type CreRegistrationsControllerUpsertRegistrationMutationBody =
  BodyType<UpsertUserCreRegistrationDto>;
export type CreRegistrationsControllerUpsertRegistrationMutationError =
  ErrorType<unknown>;

/**
 * @summary Create or update the active CRE registration for a user
 */
export const useCreRegistrationsControllerUpsertRegistration = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof creRegistrationsControllerUpsertRegistration>>,
    TError,
    { address: string; data: BodyType<UpsertUserCreRegistrationDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof creRegistrationsControllerUpsertRegistration>>,
  TError,
  { address: string; data: BodyType<UpsertUserCreRegistrationDto> },
  TContext
> => {
  return useMutation(
    getCreRegistrationsControllerUpsertRegistrationMutationOptions(options),
  );
};

/**
 * @summary Get active CRE registration for a user
 */
export type creRegistrationsControllerGetRegistrationResponse200 = {
  data: void;
  status: 200;
};

export type creRegistrationsControllerGetRegistrationResponseSuccess =
  creRegistrationsControllerGetRegistrationResponse200 & {
    headers: Headers;
  };
export type creRegistrationsControllerGetRegistrationResponse =
  creRegistrationsControllerGetRegistrationResponseSuccess;

export const getCreRegistrationsControllerGetRegistrationUrl = (
  address: string,
) => {
  return `/v1/users/${address}/cre-registration`;
};

export const creRegistrationsControllerGetRegistration = async (
  address: string,
  options?: RequestInit,
): Promise<creRegistrationsControllerGetRegistrationResponse> => {
  return customClient<creRegistrationsControllerGetRegistrationResponse>(
    getCreRegistrationsControllerGetRegistrationUrl(address),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getCreRegistrationsControllerGetRegistrationQueryKey = (
  address: string,
) => {
  return [`/v1/users/${address}/cre-registration`] as const;
};

export const getCreRegistrationsControllerGetRegistrationQueryOptions = <
  TData = Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>,
  TError = ErrorType<unknown>,
>(
  address: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCreRegistrationsControllerGetRegistrationQueryKey(address);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>
  > = ({ signal }) =>
    creRegistrationsControllerGetRegistration(address, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CreRegistrationsControllerGetRegistrationQueryResult = NonNullable<
  Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>
>;
export type CreRegistrationsControllerGetRegistrationQueryError =
  ErrorType<unknown>;

/**
 * @summary Get active CRE registration for a user
 */

export function useCreRegistrationsControllerGetRegistration<
  TData = Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>,
  TError = ErrorType<unknown>,
>(
  address: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof creRegistrationsControllerGetRegistration>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getCreRegistrationsControllerGetRegistrationQueryOptions(
    address,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List CRE registration revisions for a user
 */
export type creRegistrationsControllerListRegistrationRevisionsResponse200 = {
  data: void;
  status: 200;
};

export type creRegistrationsControllerListRegistrationRevisionsResponseSuccess =
  creRegistrationsControllerListRegistrationRevisionsResponse200 & {
    headers: Headers;
  };
export type creRegistrationsControllerListRegistrationRevisionsResponse =
  creRegistrationsControllerListRegistrationRevisionsResponseSuccess;

export const getCreRegistrationsControllerListRegistrationRevisionsUrl = (
  address: string,
  params?: CreRegistrationsControllerListRegistrationRevisionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/users/${address}/cre-registration/revisions?${stringifiedParams}`
    : `/v1/users/${address}/cre-registration/revisions`;
};

export const creRegistrationsControllerListRegistrationRevisions = async (
  address: string,
  params?: CreRegistrationsControllerListRegistrationRevisionsParams,
  options?: RequestInit,
): Promise<creRegistrationsControllerListRegistrationRevisionsResponse> => {
  return customClient<creRegistrationsControllerListRegistrationRevisionsResponse>(
    getCreRegistrationsControllerListRegistrationRevisionsUrl(address, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getCreRegistrationsControllerListRegistrationRevisionsQueryKey = (
  address: string,
  params?: CreRegistrationsControllerListRegistrationRevisionsParams,
) => {
  return [
    `/v1/users/${address}/cre-registration/revisions`,
    ...(params ? [params] : []),
  ] as const;
};

export const getCreRegistrationsControllerListRegistrationRevisionsQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
    >,
    TError = ErrorType<unknown>,
  >(
    address: string,
    params?: CreRegistrationsControllerListRegistrationRevisionsParams,
    options?: {
      query?: UseQueryOptions<
        Awaited<
          ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
        >,
        TError,
        TData
      >;
      request?: SecondParameter<typeof customClient>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getCreRegistrationsControllerListRegistrationRevisionsQueryKey(
        address,
        params,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
      >
    > = ({ signal }) =>
      creRegistrationsControllerListRegistrationRevisions(address, params, {
        signal,
        ...requestOptions,
      });

    return {
      queryKey,
      queryFn,
      enabled: !!address,
      staleTime: 10000,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
      >,
      TError,
      TData
    > & { queryKey: QueryKey };
  };

export type CreRegistrationsControllerListRegistrationRevisionsQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
    >
  >;
export type CreRegistrationsControllerListRegistrationRevisionsQueryError =
  ErrorType<unknown>;

/**
 * @summary List CRE registration revisions for a user
 */

export function useCreRegistrationsControllerListRegistrationRevisions<
  TData = Awaited<
    ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
  >,
  TError = ErrorType<unknown>,
>(
  address: string,
  params?: CreRegistrationsControllerListRegistrationRevisionsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<
        ReturnType<typeof creRegistrationsControllerListRegistrationRevisions>
      >,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getCreRegistrationsControllerListRegistrationRevisionsQueryOptions(
      address,
      params,
      options,
    );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Generate deterministic managed demo wallet from real user address
 */
export type demoWalletsControllerGenerateResponse201 = {
  data: void;
  status: 201;
};

export type demoWalletsControllerGenerateResponseSuccess =
  demoWalletsControllerGenerateResponse201 & {
    headers: Headers;
  };
export type demoWalletsControllerGenerateResponse =
  demoWalletsControllerGenerateResponseSuccess;

export const getDemoWalletsControllerGenerateUrl = () => {
  return `/v1/demo-wallets/generate`;
};

export const demoWalletsControllerGenerate = async (
  generateDemoWalletDto: GenerateDemoWalletDto,
  options?: RequestInit,
): Promise<demoWalletsControllerGenerateResponse> => {
  return customClient<demoWalletsControllerGenerateResponse>(
    getDemoWalletsControllerGenerateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(generateDemoWalletDto),
    },
  );
};

export const getDemoWalletsControllerGenerateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof demoWalletsControllerGenerate>>,
    TError,
    { data: BodyType<GenerateDemoWalletDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof demoWalletsControllerGenerate>>,
  TError,
  { data: BodyType<GenerateDemoWalletDto> },
  TContext
> => {
  const mutationKey = ["demoWalletsControllerGenerate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof demoWalletsControllerGenerate>>,
    { data: BodyType<GenerateDemoWalletDto> }
  > = (props) => {
    const { data } = props ?? {};

    return demoWalletsControllerGenerate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DemoWalletsControllerGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof demoWalletsControllerGenerate>>
>;
export type DemoWalletsControllerGenerateMutationBody =
  BodyType<GenerateDemoWalletDto>;
export type DemoWalletsControllerGenerateMutationError = ErrorType<unknown>;

/**
 * @summary Generate deterministic managed demo wallet from real user address
 */
export const useDemoWalletsControllerGenerate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof demoWalletsControllerGenerate>>,
    TError,
    { data: BodyType<GenerateDemoWalletDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof demoWalletsControllerGenerate>>,
  TError,
  { data: BodyType<GenerateDemoWalletDto> },
  TContext
> => {
  return useMutation(getDemoWalletsControllerGenerateMutationOptions(options));
};

/**
 * @summary Mint demo balances and fund native gas on supported chains
 */
export type demoWalletsControllerFundResponse201 = {
  data: void;
  status: 201;
};

export type demoWalletsControllerFundResponseSuccess =
  demoWalletsControllerFundResponse201 & {
    headers: Headers;
  };
export type demoWalletsControllerFundResponse =
  demoWalletsControllerFundResponseSuccess;

export const getDemoWalletsControllerFundUrl = (demoWalletAddress: string) => {
  return `/v1/demo-wallets/${demoWalletAddress}/fund`;
};

export const demoWalletsControllerFund = async (
  demoWalletAddress: string,
  fundDemoWalletDto: FundDemoWalletDto,
  options?: RequestInit,
): Promise<demoWalletsControllerFundResponse> => {
  return customClient<demoWalletsControllerFundResponse>(
    getDemoWalletsControllerFundUrl(demoWalletAddress),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(fundDemoWalletDto),
    },
  );
};

export const getDemoWalletsControllerFundMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof demoWalletsControllerFund>>,
    TError,
    { demoWalletAddress: string; data: BodyType<FundDemoWalletDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof demoWalletsControllerFund>>,
  TError,
  { demoWalletAddress: string; data: BodyType<FundDemoWalletDto> },
  TContext
> => {
  const mutationKey = ["demoWalletsControllerFund"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof demoWalletsControllerFund>>,
    { demoWalletAddress: string; data: BodyType<FundDemoWalletDto> }
  > = (props) => {
    const { demoWalletAddress, data } = props ?? {};

    return demoWalletsControllerFund(demoWalletAddress, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DemoWalletsControllerFundMutationResult = NonNullable<
  Awaited<ReturnType<typeof demoWalletsControllerFund>>
>;
export type DemoWalletsControllerFundMutationBody = BodyType<FundDemoWalletDto>;
export type DemoWalletsControllerFundMutationError = ErrorType<unknown>;

/**
 * @summary Mint demo balances and fund native gas on supported chains
 */
export const useDemoWalletsControllerFund = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof demoWalletsControllerFund>>,
    TError,
    { demoWalletAddress: string; data: BodyType<FundDemoWalletDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof demoWalletsControllerFund>>,
  TError,
  { demoWalletAddress: string; data: BodyType<FundDemoWalletDto> },
  TContext
> => {
  return useMutation(getDemoWalletsControllerFundMutationOptions(options));
};

/**
 * @summary Bootstrap demo wallet positions for rescue scenarios across Ethereum/Base Sepolia
 */
export type demoWalletsControllerBootstrapPositionsResponse201 = {
  data: void;
  status: 201;
};

export type demoWalletsControllerBootstrapPositionsResponseSuccess =
  demoWalletsControllerBootstrapPositionsResponse201 & {
    headers: Headers;
  };
export type demoWalletsControllerBootstrapPositionsResponse =
  demoWalletsControllerBootstrapPositionsResponseSuccess;

export const getDemoWalletsControllerBootstrapPositionsUrl = (
  demoWalletAddress: string,
) => {
  return `/v1/demo-wallets/${demoWalletAddress}/bootstrap-positions`;
};

export const demoWalletsControllerBootstrapPositions = async (
  demoWalletAddress: string,
  bootstrapDemoWalletDto: BootstrapDemoWalletDto,
  options?: RequestInit,
): Promise<demoWalletsControllerBootstrapPositionsResponse> => {
  return customClient<demoWalletsControllerBootstrapPositionsResponse>(
    getDemoWalletsControllerBootstrapPositionsUrl(demoWalletAddress),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(bootstrapDemoWalletDto),
    },
  );
};

export const getDemoWalletsControllerBootstrapPositionsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof demoWalletsControllerBootstrapPositions>>,
    TError,
    { demoWalletAddress: string; data: BodyType<BootstrapDemoWalletDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof demoWalletsControllerBootstrapPositions>>,
  TError,
  { demoWalletAddress: string; data: BodyType<BootstrapDemoWalletDto> },
  TContext
> => {
  const mutationKey = ["demoWalletsControllerBootstrapPositions"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof demoWalletsControllerBootstrapPositions>>,
    { demoWalletAddress: string; data: BodyType<BootstrapDemoWalletDto> }
  > = (props) => {
    const { demoWalletAddress, data } = props ?? {};

    return demoWalletsControllerBootstrapPositions(
      demoWalletAddress,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type DemoWalletsControllerBootstrapPositionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof demoWalletsControllerBootstrapPositions>>
>;
export type DemoWalletsControllerBootstrapPositionsMutationBody =
  BodyType<BootstrapDemoWalletDto>;
export type DemoWalletsControllerBootstrapPositionsMutationError =
  ErrorType<unknown>;

/**
 * @summary Bootstrap demo wallet positions for rescue scenarios across Ethereum/Base Sepolia
 */
export const useDemoWalletsControllerBootstrapPositions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof demoWalletsControllerBootstrapPositions>>,
    TError,
    { demoWalletAddress: string; data: BodyType<BootstrapDemoWalletDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof demoWalletsControllerBootstrapPositions>>,
  TError,
  { demoWalletAddress: string; data: BodyType<BootstrapDemoWalletDto> },
  TContext
> => {
  return useMutation(
    getDemoWalletsControllerBootstrapPositionsMutationOptions(options),
  );
};

/**
 * @summary Get latest known positions for a wallet address
 */
export type positionsControllerGetPositionsResponse200 = {
  data: void;
  status: 200;
};

export type positionsControllerGetPositionsResponseSuccess =
  positionsControllerGetPositionsResponse200 & {
    headers: Headers;
  };
export type positionsControllerGetPositionsResponse =
  positionsControllerGetPositionsResponseSuccess;

export const getPositionsControllerGetPositionsUrl = (address: string) => {
  return `/v1/positions/${address}`;
};

export const positionsControllerGetPositions = async (
  address: string,
  options?: RequestInit,
): Promise<positionsControllerGetPositionsResponse> => {
  return customClient<positionsControllerGetPositionsResponse>(
    getPositionsControllerGetPositionsUrl(address),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPositionsControllerGetPositionsQueryKey = (address: string) => {
  return [`/v1/positions/${address}`] as const;
};

export const getPositionsControllerGetPositionsQueryOptions = <
  TData = Awaited<ReturnType<typeof positionsControllerGetPositions>>,
  TError = ErrorType<unknown>,
>(
  address: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof positionsControllerGetPositions>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPositionsControllerGetPositionsQueryKey(address);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof positionsControllerGetPositions>>
  > = ({ signal }) =>
    positionsControllerGetPositions(address, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof positionsControllerGetPositions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PositionsControllerGetPositionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof positionsControllerGetPositions>>
>;
export type PositionsControllerGetPositionsQueryError = ErrorType<unknown>;

/**
 * @summary Get latest known positions for a wallet address
 */

export function usePositionsControllerGetPositions<
  TData = Awaited<ReturnType<typeof positionsControllerGetPositions>>,
  TError = ErrorType<unknown>,
>(
  address: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof positionsControllerGetPositions>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPositionsControllerGetPositionsQueryOptions(
    address,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get CRE-ready risk snapshot (cross-chain aggregated positions)
 */
export type positionsControllerGetRiskSnapshotResponse200 = {
  data: void;
  status: 200;
};

export type positionsControllerGetRiskSnapshotResponseSuccess =
  positionsControllerGetRiskSnapshotResponse200 & {
    headers: Headers;
  };
export type positionsControllerGetRiskSnapshotResponse =
  positionsControllerGetRiskSnapshotResponseSuccess;

export const getPositionsControllerGetRiskSnapshotUrl = (
  address: string,
  params?: PositionsControllerGetRiskSnapshotParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/positions/${address}/risk-snapshot?${stringifiedParams}`
    : `/v1/positions/${address}/risk-snapshot`;
};

export const positionsControllerGetRiskSnapshot = async (
  address: string,
  params?: PositionsControllerGetRiskSnapshotParams,
  options?: RequestInit,
): Promise<positionsControllerGetRiskSnapshotResponse> => {
  return customClient<positionsControllerGetRiskSnapshotResponse>(
    getPositionsControllerGetRiskSnapshotUrl(address, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPositionsControllerGetRiskSnapshotQueryKey = (
  address: string,
  params?: PositionsControllerGetRiskSnapshotParams,
) => {
  return [
    `/v1/positions/${address}/risk-snapshot`,
    ...(params ? [params] : []),
  ] as const;
};

export const getPositionsControllerGetRiskSnapshotQueryOptions = <
  TData = Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>,
  TError = ErrorType<unknown>,
>(
  address: string,
  params?: PositionsControllerGetRiskSnapshotParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPositionsControllerGetRiskSnapshotQueryKey(address, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>
  > = ({ signal }) =>
    positionsControllerGetRiskSnapshot(address, params, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PositionsControllerGetRiskSnapshotQueryResult = NonNullable<
  Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>
>;
export type PositionsControllerGetRiskSnapshotQueryError = ErrorType<unknown>;

/**
 * @summary Get CRE-ready risk snapshot (cross-chain aggregated positions)
 */

export function usePositionsControllerGetRiskSnapshot<
  TData = Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>,
  TError = ErrorType<unknown>,
>(
  address: string,
  params?: PositionsControllerGetRiskSnapshotParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof positionsControllerGetRiskSnapshot>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPositionsControllerGetRiskSnapshotQueryOptions(
    address,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List relay jobs with filters and pagination
 */
export type relayControllerListRelayJobsResponse200 = {
  data: void;
  status: 200;
};

export type relayControllerListRelayJobsResponseSuccess =
  relayControllerListRelayJobsResponse200 & {
    headers: Headers;
  };
export type relayControllerListRelayJobsResponse =
  relayControllerListRelayJobsResponseSuccess;

export const getRelayControllerListRelayJobsUrl = (
  params?: RelayControllerListRelayJobsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/relay/jobs?${stringifiedParams}`
    : `/v1/relay/jobs`;
};

export const relayControllerListRelayJobs = async (
  params?: RelayControllerListRelayJobsParams,
  options?: RequestInit,
): Promise<relayControllerListRelayJobsResponse> => {
  return customClient<relayControllerListRelayJobsResponse>(
    getRelayControllerListRelayJobsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRelayControllerListRelayJobsQueryKey = (
  params?: RelayControllerListRelayJobsParams,
) => {
  return [`/v1/relay/jobs`, ...(params ? [params] : [])] as const;
};

export const getRelayControllerListRelayJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof relayControllerListRelayJobs>>,
  TError = ErrorType<unknown>,
>(
  params?: RelayControllerListRelayJobsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof relayControllerListRelayJobs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRelayControllerListRelayJobsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof relayControllerListRelayJobs>>
  > = ({ signal }) =>
    relayControllerListRelayJobs(params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof relayControllerListRelayJobs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RelayControllerListRelayJobsQueryResult = NonNullable<
  Awaited<ReturnType<typeof relayControllerListRelayJobs>>
>;
export type RelayControllerListRelayJobsQueryError = ErrorType<unknown>;

/**
 * @summary List relay jobs with filters and pagination
 */

export function useRelayControllerListRelayJobs<
  TData = Awaited<ReturnType<typeof relayControllerListRelayJobs>>,
  TError = ErrorType<unknown>,
>(
  params?: RelayControllerListRelayJobsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof relayControllerListRelayJobs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRelayControllerListRelayJobsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get one relay job by message id
 */
export type relayControllerGetRelayJobResponse200 = {
  data: void;
  status: 200;
};

export type relayControllerGetRelayJobResponseSuccess =
  relayControllerGetRelayJobResponse200 & {
    headers: Headers;
  };
export type relayControllerGetRelayJobResponse =
  relayControllerGetRelayJobResponseSuccess;

export const getRelayControllerGetRelayJobUrl = (messageId: string) => {
  return `/v1/relay/jobs/${messageId}`;
};

export const relayControllerGetRelayJob = async (
  messageId: string,
  options?: RequestInit,
): Promise<relayControllerGetRelayJobResponse> => {
  return customClient<relayControllerGetRelayJobResponse>(
    getRelayControllerGetRelayJobUrl(messageId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRelayControllerGetRelayJobQueryKey = (messageId: string) => {
  return [`/v1/relay/jobs/${messageId}`] as const;
};

export const getRelayControllerGetRelayJobQueryOptions = <
  TData = Awaited<ReturnType<typeof relayControllerGetRelayJob>>,
  TError = ErrorType<unknown>,
>(
  messageId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof relayControllerGetRelayJob>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRelayControllerGetRelayJobQueryKey(messageId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof relayControllerGetRelayJob>>
  > = ({ signal }) =>
    relayControllerGetRelayJob(messageId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!messageId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof relayControllerGetRelayJob>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RelayControllerGetRelayJobQueryResult = NonNullable<
  Awaited<ReturnType<typeof relayControllerGetRelayJob>>
>;
export type RelayControllerGetRelayJobQueryError = ErrorType<unknown>;

/**
 * @summary Get one relay job by message id
 */

export function useRelayControllerGetRelayJob<
  TData = Awaited<ReturnType<typeof relayControllerGetRelayJob>>,
  TError = ErrorType<unknown>,
>(
  messageId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof relayControllerGetRelayJob>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRelayControllerGetRelayJobQueryOptions(
    messageId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Manually retry a relay job (sets status back to pending)
 */
export type relayControllerRetryRelayJobResponse201 = {
  data: void;
  status: 201;
};

export type relayControllerRetryRelayJobResponseSuccess =
  relayControllerRetryRelayJobResponse201 & {
    headers: Headers;
  };
export type relayControllerRetryRelayJobResponse =
  relayControllerRetryRelayJobResponseSuccess;

export const getRelayControllerRetryRelayJobUrl = (messageId: string) => {
  return `/v1/relay/jobs/${messageId}/retry`;
};

export const relayControllerRetryRelayJob = async (
  messageId: string,
  options?: RequestInit,
): Promise<relayControllerRetryRelayJobResponse> => {
  return customClient<relayControllerRetryRelayJobResponse>(
    getRelayControllerRetryRelayJobUrl(messageId),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getRelayControllerRetryRelayJobMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof relayControllerRetryRelayJob>>,
    TError,
    { messageId: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof relayControllerRetryRelayJob>>,
  TError,
  { messageId: string },
  TContext
> => {
  const mutationKey = ["relayControllerRetryRelayJob"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof relayControllerRetryRelayJob>>,
    { messageId: string }
  > = (props) => {
    const { messageId } = props ?? {};

    return relayControllerRetryRelayJob(messageId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RelayControllerRetryRelayJobMutationResult = NonNullable<
  Awaited<ReturnType<typeof relayControllerRetryRelayJob>>
>;

export type RelayControllerRetryRelayJobMutationError = ErrorType<unknown>;

/**
 * @summary Manually retry a relay job (sets status back to pending)
 */
export const useRelayControllerRetryRelayJob = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof relayControllerRetryRelayJob>>,
    TError,
    { messageId: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof relayControllerRetryRelayJob>>,
  TError,
  { messageId: string },
  TContext
> => {
  return useMutation(getRelayControllerRetryRelayJobMutationOptions(options));
};

/**
 * @summary List rescue executions with filters and pagination
 */
export type rescuesControllerListRescuesResponse200 = {
  data: void;
  status: 200;
};

export type rescuesControllerListRescuesResponseSuccess =
  rescuesControllerListRescuesResponse200 & {
    headers: Headers;
  };
export type rescuesControllerListRescuesResponse =
  rescuesControllerListRescuesResponseSuccess;

export const getRescuesControllerListRescuesUrl = (
  params?: RescuesControllerListRescuesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/rescues?${stringifiedParams}`
    : `/v1/rescues`;
};

export const rescuesControllerListRescues = async (
  params?: RescuesControllerListRescuesParams,
  options?: RequestInit,
): Promise<rescuesControllerListRescuesResponse> => {
  return customClient<rescuesControllerListRescuesResponse>(
    getRescuesControllerListRescuesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRescuesControllerListRescuesQueryKey = (
  params?: RescuesControllerListRescuesParams,
) => {
  return [`/v1/rescues`, ...(params ? [params] : [])] as const;
};

export const getRescuesControllerListRescuesQueryOptions = <
  TData = Awaited<ReturnType<typeof rescuesControllerListRescues>>,
  TError = ErrorType<unknown>,
>(
  params?: RescuesControllerListRescuesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerListRescues>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRescuesControllerListRescuesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rescuesControllerListRescues>>
  > = ({ signal }) =>
    rescuesControllerListRescues(params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof rescuesControllerListRescues>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RescuesControllerListRescuesQueryResult = NonNullable<
  Awaited<ReturnType<typeof rescuesControllerListRescues>>
>;
export type RescuesControllerListRescuesQueryError = ErrorType<unknown>;

/**
 * @summary List rescue executions with filters and pagination
 */

export function useRescuesControllerListRescues<
  TData = Awaited<ReturnType<typeof rescuesControllerListRescues>>,
  TError = ErrorType<unknown>,
>(
  params?: RescuesControllerListRescuesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerListRescues>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRescuesControllerListRescuesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get rescue execution aggregate by execId
 */
export type rescuesControllerGetRescueResponse200 = {
  data: void;
  status: 200;
};

export type rescuesControllerGetRescueResponseSuccess =
  rescuesControllerGetRescueResponse200 & {
    headers: Headers;
  };
export type rescuesControllerGetRescueResponse =
  rescuesControllerGetRescueResponseSuccess;

export const getRescuesControllerGetRescueUrl = (execId: string) => {
  return `/v1/rescues/${execId}`;
};

export const rescuesControllerGetRescue = async (
  execId: string,
  options?: RequestInit,
): Promise<rescuesControllerGetRescueResponse> => {
  return customClient<rescuesControllerGetRescueResponse>(
    getRescuesControllerGetRescueUrl(execId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRescuesControllerGetRescueQueryKey = (execId: string) => {
  return [`/v1/rescues/${execId}`] as const;
};

export const getRescuesControllerGetRescueQueryOptions = <
  TData = Awaited<ReturnType<typeof rescuesControllerGetRescue>>,
  TError = ErrorType<unknown>,
>(
  execId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerGetRescue>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRescuesControllerGetRescueQueryKey(execId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rescuesControllerGetRescue>>
  > = ({ signal }) =>
    rescuesControllerGetRescue(execId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!execId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof rescuesControllerGetRescue>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RescuesControllerGetRescueQueryResult = NonNullable<
  Awaited<ReturnType<typeof rescuesControllerGetRescue>>
>;
export type RescuesControllerGetRescueQueryError = ErrorType<unknown>;

/**
 * @summary Get rescue execution aggregate by execId
 */

export function useRescuesControllerGetRescue<
  TData = Awaited<ReturnType<typeof rescuesControllerGetRescue>>,
  TError = ErrorType<unknown>,
>(
  execId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerGetRescue>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRescuesControllerGetRescueQueryOptions(
    execId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get ordered raw events for a rescue execId
 */
export type rescuesControllerGetRescueEventsResponse200 = {
  data: void;
  status: 200;
};

export type rescuesControllerGetRescueEventsResponseSuccess =
  rescuesControllerGetRescueEventsResponse200 & {
    headers: Headers;
  };
export type rescuesControllerGetRescueEventsResponse =
  rescuesControllerGetRescueEventsResponseSuccess;

export const getRescuesControllerGetRescueEventsUrl = (execId: string) => {
  return `/v1/rescues/${execId}/events`;
};

export const rescuesControllerGetRescueEvents = async (
  execId: string,
  options?: RequestInit,
): Promise<rescuesControllerGetRescueEventsResponse> => {
  return customClient<rescuesControllerGetRescueEventsResponse>(
    getRescuesControllerGetRescueEventsUrl(execId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRescuesControllerGetRescueEventsQueryKey = (execId: string) => {
  return [`/v1/rescues/${execId}/events`] as const;
};

export const getRescuesControllerGetRescueEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>,
  TError = ErrorType<unknown>,
>(
  execId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRescuesControllerGetRescueEventsQueryKey(execId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>
  > = ({ signal }) =>
    rescuesControllerGetRescueEvents(execId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!execId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RescuesControllerGetRescueEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>
>;
export type RescuesControllerGetRescueEventsQueryError = ErrorType<unknown>;

/**
 * @summary Get ordered raw events for a rescue execId
 */

export function useRescuesControllerGetRescueEvents<
  TData = Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>,
  TError = ErrorType<unknown>,
>(
  execId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerGetRescueEvents>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRescuesControllerGetRescueEventsQueryOptions(
    execId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Store a CRE workflow log mapped to rescue execution
 */
export type rescuesControllerCreateRescueWorkflowLogResponse201 = {
  data: void;
  status: 201;
};

export type rescuesControllerCreateRescueWorkflowLogResponseSuccess =
  rescuesControllerCreateRescueWorkflowLogResponse201 & {
    headers: Headers;
  };
export type rescuesControllerCreateRescueWorkflowLogResponse =
  rescuesControllerCreateRescueWorkflowLogResponseSuccess;

export const getRescuesControllerCreateRescueWorkflowLogUrl = (
  execId: string,
) => {
  return `/v1/rescues/${execId}/cre-logs`;
};

export const rescuesControllerCreateRescueWorkflowLog = async (
  execId: string,
  createRescueWorkflowLogDto: CreateRescueWorkflowLogDto,
  options?: RequestInit,
): Promise<rescuesControllerCreateRescueWorkflowLogResponse> => {
  return customClient<rescuesControllerCreateRescueWorkflowLogResponse>(
    getRescuesControllerCreateRescueWorkflowLogUrl(execId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createRescueWorkflowLogDto),
    },
  );
};

export const getRescuesControllerCreateRescueWorkflowLogMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rescuesControllerCreateRescueWorkflowLog>>,
    TError,
    { execId: string; data: BodyType<CreateRescueWorkflowLogDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rescuesControllerCreateRescueWorkflowLog>>,
  TError,
  { execId: string; data: BodyType<CreateRescueWorkflowLogDto> },
  TContext
> => {
  const mutationKey = ["rescuesControllerCreateRescueWorkflowLog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rescuesControllerCreateRescueWorkflowLog>>,
    { execId: string; data: BodyType<CreateRescueWorkflowLogDto> }
  > = (props) => {
    const { execId, data } = props ?? {};

    return rescuesControllerCreateRescueWorkflowLog(
      execId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type RescuesControllerCreateRescueWorkflowLogMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof rescuesControllerCreateRescueWorkflowLog>>
  >;
export type RescuesControllerCreateRescueWorkflowLogMutationBody =
  BodyType<CreateRescueWorkflowLogDto>;
export type RescuesControllerCreateRescueWorkflowLogMutationError =
  ErrorType<unknown>;

/**
 * @summary Store a CRE workflow log mapped to rescue execution
 */
export const useRescuesControllerCreateRescueWorkflowLog = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rescuesControllerCreateRescueWorkflowLog>>,
    TError,
    { execId: string; data: BodyType<CreateRescueWorkflowLogDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof rescuesControllerCreateRescueWorkflowLog>>,
  TError,
  { execId: string; data: BodyType<CreateRescueWorkflowLogDto> },
  TContext
> => {
  return useMutation(
    getRescuesControllerCreateRescueWorkflowLogMutationOptions(options),
  );
};

/**
 * @summary List CRE workflow logs for a rescue execution
 */
export type rescuesControllerListRescueWorkflowLogsResponse200 = {
  data: void;
  status: 200;
};

export type rescuesControllerListRescueWorkflowLogsResponseSuccess =
  rescuesControllerListRescueWorkflowLogsResponse200 & {
    headers: Headers;
  };
export type rescuesControllerListRescueWorkflowLogsResponse =
  rescuesControllerListRescueWorkflowLogsResponseSuccess;

export const getRescuesControllerListRescueWorkflowLogsUrl = (
  execId: string,
  params?: RescuesControllerListRescueWorkflowLogsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/rescues/${execId}/cre-logs?${stringifiedParams}`
    : `/v1/rescues/${execId}/cre-logs`;
};

export const rescuesControllerListRescueWorkflowLogs = async (
  execId: string,
  params?: RescuesControllerListRescueWorkflowLogsParams,
  options?: RequestInit,
): Promise<rescuesControllerListRescueWorkflowLogsResponse> => {
  return customClient<rescuesControllerListRescueWorkflowLogsResponse>(
    getRescuesControllerListRescueWorkflowLogsUrl(execId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRescuesControllerListRescueWorkflowLogsQueryKey = (
  execId: string,
  params?: RescuesControllerListRescueWorkflowLogsParams,
) => {
  return [
    `/v1/rescues/${execId}/cre-logs`,
    ...(params ? [params] : []),
  ] as const;
};

export const getRescuesControllerListRescueWorkflowLogsQueryOptions = <
  TData = Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>,
  TError = ErrorType<unknown>,
>(
  execId: string,
  params?: RescuesControllerListRescueWorkflowLogsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRescuesControllerListRescueWorkflowLogsQueryKey(execId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>
  > = ({ signal }) =>
    rescuesControllerListRescueWorkflowLogs(execId, params, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!execId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RescuesControllerListRescueWorkflowLogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>
>;
export type RescuesControllerListRescueWorkflowLogsQueryError =
  ErrorType<unknown>;

/**
 * @summary List CRE workflow logs for a rescue execution
 */

export function useRescuesControllerListRescueWorkflowLogs<
  TData = Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>,
  TError = ErrorType<unknown>,
>(
  execId: string,
  params?: RescuesControllerListRescueWorkflowLogsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof rescuesControllerListRescueWorkflowLogs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRescuesControllerListRescueWorkflowLogsQueryOptions(
    execId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Health check endpoint
 */
export type healthControllerGetHealthResponse200 = {
  data: void;
  status: 200;
};

export type healthControllerGetHealthResponseSuccess =
  healthControllerGetHealthResponse200 & {
    headers: Headers;
  };
export type healthControllerGetHealthResponse =
  healthControllerGetHealthResponseSuccess;

export const getHealthControllerGetHealthUrl = () => {
  return `/v1/health`;
};

export const healthControllerGetHealth = async (
  options?: RequestInit,
): Promise<healthControllerGetHealthResponse> => {
  return customClient<healthControllerGetHealthResponse>(
    getHealthControllerGetHealthUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getHealthControllerGetHealthQueryKey = () => {
  return [`/v1/health`] as const;
};

export const getHealthControllerGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerGetHealth>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerGetHealth>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHealthControllerGetHealthQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerGetHealth>>
  > = ({ signal }) => healthControllerGetHealth({ signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerGetHealth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthControllerGetHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerGetHealth>>
>;
export type HealthControllerGetHealthQueryError = ErrorType<unknown>;

/**
 * @summary Health check endpoint
 */

export function useHealthControllerGetHealth<
  TData = Awaited<ReturnType<typeof healthControllerGetHealth>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerGetHealth>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthControllerGetHealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
